name: Update README Date

on:
  push:
    paths:
      - 'README.md'
    branches:
      - main

jobs:
  update-readme-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README date
        run: |
          DATE=$(date +"%B %Y")
          sed -i "s/<!-- LAST_UPDATED -->.*/<!-- LAST_UPDATED --> $DATE/" README.md
      - name: Commit updated README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update README date"
